<a href="https://ondiande.com/contact/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="ONDIA Contact" width="110" height="200" title="This notebook is licensed by ONDIA. Please contact the authorized persons about the conditions under which you can use or share."></a>

<div style="background-color:#8CCED1; font-family:newtimeroman; color:#635EA7; font-size:200%; text-align:center; border-radius:10px 10px; margin-top:20px; margin-bottom:20px; padding-top:15px; padding-bottom:15px; font-weight:bold;"></div>

<p style="text-align: center;"> <a href="https://ondiande.com/"> <img src="https://i.ibb.co/mvHRT4S/ONDIA-logo.png" width="500" height="200" class="img-fluid" alt="ONDIA LOGO" title="INTELLIGENT & PERSONALIZED SOLUTIONS TO DATA ANALYSIS AND DATA MANAGEMENT ISSUES"> </a> </p>

<div style="background-color:#58B8E4; font-family:newtimeroman; color:#635EA7; font-size:200%; text-align:center; border-radius:10px 10px; margin-top:20px; margin-bottom:20px; padding-top:15px; padding-bottom:15px; font-weight:bold;">
  Intelligent & Personalized Solutions
</div>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:300%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

<div style="background-color:#8CCED1; font-family:newtimeroman; color:#635EA7; font-size:200%; text-align:center; border-radius:10px 10px; margin-top:20px; margin-bottom:20px; padding-top:15px; padding-bottom:15px; font-weight:bold;"></div>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<div style="background-color:#58B8E4; font-family:newtimeroman; color:#635EA7; font-size:200%; text-align:center; border-radius:10px 10px; margin-top:20px; margin-bottom:20px; padding-top:15px; padding-bottom:15px; font-weight:bold;"></div>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [1]:
# YOUR CODE IS HERE
import numpy as np


### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [5]:
# YOUR CODE IS HERE
my_list = [5, 10, 15, 20, 25]
np.array(my_list)

array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros.

In [25]:
# YOUR CODE IS HERE

np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [41]:
# YOUR CODE IS HERE
np.ones((4,4),dtype = "int8")


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

### 5. Make all the values of the array above with the value of 7.

In [61]:
# YOUR CODE IS HERE
np.ones((4,4),dtype = "int8") *7



array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]], dtype=int8)

### 6. Create the previous array above by full() method.

In [71]:
# YOUR CODE IS HERE
np.full((4,4), 7, dtype="int8")


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]], dtype=int8)

### 7. Create an array of even integers from 2 to 16 (inclusive).

In [82]:
# YOUR CODE IS HERE
arr = np.arange(2,16,2)
arr


array([ 2,  4,  6,  8, 10, 12, 14])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [86]:
# YOUR CODE IS HERE

a = np.arange(0,25)
a.reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [105]:
# YOUR CODE IS HERE

b = np.linspace(0,24, num=25, dtype='int8').reshape((5,5))
b


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]], dtype=int8)

### 10. Create randomly 5 numbers with numpy.

In [121]:
# YOUR CODE IS HERE

a = np.random.randint(0,6,5)
a

array([5, 2, 5, 0, 5])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [133]:
# YOUR CODE IS HERE
np.random.seed(42)

a3 = np.random.randn(5, 5)

a3

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337],
       [-0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783],
       [-0.56228753, -1.01283112,  0.31424733, -0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819, -0.54438272]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [141]:
# YOUR CODE IS HERE

bb = np.random.randint(20,50, size=(3,4))
bb


array([[45, 40, 21, 39],
       [47, 34, 47, 26],
       [31, 48, 27, 34]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [149]:
# YOUR CODE IS HERE

ranarr = np.random.randint(0,47 ,size=48)
ranarr

array([35, 39,  3,  1,  5, 41,  3, 28, 17, 25, 43, 33,  9, 35, 13, 30, 14,
        7, 13, 22, 39, 20, 15, 44, 17, 46, 23, 25, 24, 44, 40, 28, 14, 44,
        0, 24,  6,  8, 23,  0, 43,  7, 23, 10, 16,  7, 34, 34])

In [151]:
# YOUR CODE IS HERE (RESHAPING WITH NUM)

ranarr = np.random.randint(0,47 ,size=(6,8))
ranarr

array([[32,  4, 41, 38, 40, 27,  6,  8],
       [ 7, 11, 33, 32, 22, 23, 36, 34],
       [43, 39, 21, 26, 34,  0, 34, 36],
       [46, 13,  2,  0,  4, 25, 13, 38],
       [26,  8, 14, 14, 25, 41, 12, 31],
       [38, 31,  3, 29, 36, 22, 38, 44]])

In [153]:
# YOUR CODE IS HERE (RESHAPING WITH -1)

ranarr = np.random.randint(0,47 ,size=(1,6,8))
ranarr

array([[[14, 42, 28, 35, 12, 31,  6, 21],
        [27,  1, 41, 44,  5, 27, 27, 43],
        [43, 19, 29, 10, 27, 24, 38, 32],
        [ 0, 26, 12, 40,  2, 38,  5,  7],
        [26,  8, 36, 32, 41, 43, 23, 14],
        [31, 31, 23, 40, 11, 38,  1,  2]]])

In [167]:
# YOUR CODE IS HERE (RESHAPING WITH -1)

ranarr = np.random.randint(0,47)
ranarr


36

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [224]:
# YOUR CODE IS HERE
a = ([1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12], [13, 14, 15, 16])
np.array(a)

mat=np.array(a)

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [227]:
# YOUR CODE IS HERE
fd= mat[1:3, 1:3]
fd


array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [234]:
# YOUR CODE IS HERE
mat[:,0]

array([ 1,  5,  9, 13])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [237]:
# YOUR CODE IS HERE
mat[1,::2]

array([5, 7])

### 17.Assign 77 to every cell in 3rd column.

In [240]:
# YOUR CODE IS HERE
mat[:,2] = 77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [243]:
# YOUR CODE IS HERE
np.array([mat[1, 0], mat[3, 2]])

array([ 5, 77])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [246]:
# YOUR CODE IS HERE
mat[1::2,0::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [265]:
# LET US REMEMBER OUR ARRAY OF "mat"

# YOUR CODE IS HERE

mat[(mat < 10) & (mat >12)]



array([], dtype=int64)

In [267]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat"

# YOUR CODE IS HERE

mat[(mat < 10)]

array([1, 2, 4, 5, 6, 8, 9])

In [269]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat"

# YOUR CODE IS HERE

mat[(mat >12)]

array([77, 77, 77, 13, 14, 77, 16])

In [295]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat"

# YOUR CODE IS HERE
c = mat[(mat >12)] + mat[(mat < 10)]
c


array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [297]:
# YOUR CODE IS HERE
c.std()


np.float64(29.700546274093877)

### 22. Get the sum of the 2nd column in the original "mat".

In [299]:
# LET US REMEMBER OUR ARRAY OF "mat"

# YOUR CODE IS HERE

mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [301]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat"

# YOUR CODE IS HERE
mat[:, 2] = [3, 7, 11, 15] 
mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# YOUR CODE IS HERE



### 23. Get the median, mean and std of 3rd column in "mat".

In [303]:
# LET US REMEMBER OUR ARRAY OF "mat"

# YOUR CODE IS HERE

mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [319]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE

# YOUR CODE IS HERE

kolon = mat[:,2]
np.array(kolon).reshape(4,1)


array([[ 3],
       [ 7],
       [11],
       [15]])

In [323]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW?

# YOUR CODE IS HERE
sutunuc = mat[2,:]
sutunuc


array([ 9, 10, 11, 12])

In [379]:
# LET US GET MEDIAN VALUE

# YOUR CODE IS HERE

print(np.median(kolon))
print(np.median(sutunuc))

9.0
10.5


In [381]:
# LET US GET MEAN VALUE

# YOUR CODE IS HERE
np.mean(mat)
print(np.mean(kolon))
print(np.mean(sutunuc))

9.0
10.5


In [383]:
# LET US GET STANDART DEVIATION (std) VALUE

# YOUR CODE IS HERE

print(np.std(kolon))
print(np.std(sutunuc))

4.47213595499958
1.118033988749895


## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [385]:
import pandas as pd

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [390]:
# LET US READ Salaries.csv

# YOUR CODE IS HERE
df = pd.read_csv("/Users/zaferyildirim/Desktop/Salaries.csv")


In [392]:
# LET US LOOK AT THE FIRST 5 ROWS

# YOUR CODE IS HERE

df.head(5)

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [394]:
# LET US GET A SAMPLE

# YOUR CODE IS HERE

df.sample()


Id EmployeeName     JobTitle   BasePay  OvertimePay  OtherPay  \
52407  52408  Sarah Stone  Librarian 1  74048.53          0.0   1490.97   

       Benefits  TotalPay  TotalPayBenefits  Year  Notes         Agency  \
52407  33147.17   75539.5         108686.67  2012    NaN  San Francisco   

       Status  
52407     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [396]:
# YOUR CODE IS HERE
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [398]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS

# YOUR CODE IS HERE
df.describe()


Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448840    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [408]:
# YOUR CODE IS HERE

df['Year'].value_counts()



Year
2014    38123
2013    37606
2012    36766
2011    36159
Name: count, dtype: int64

In [412]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE
df['Year'].nunique()



4

In [414]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE

df['Year'].unique()


array([2011, 2012, 2013, 2014])

### Print out max and avg values in the column of "Totalpay".

In [428]:
# LET US FIND THE MAXIMUM TOTALPAY

# YOUR CODE IS HERE
df["TotalPay"].max()


np.float64(567595.43)

In [432]:
# LET US FIND THE AVERAGE TOTALPAY

# YOUR CODE IS HERE
df["TotalPay"].mena()



np.float64(74768.32197169267)

### How many records in the TotalPay column are there bigger than avg TotalPay?

In [467]:
# YOUR CODE IS HERE


tot = df["TotalPay"].mean()



upp = df[(df['TotalPay'] > tot)]

upp

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
135701  135702    Christina S Jee   
135778  135779  Mary Ann T Abille   
135847  135848   Emilda E Reinosa   
135853  135854      David G Evans   
136063  136064         Nicole Joe   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
135701                              Nurse Practitioner   70635.61   
135778                                   Special Nurse   60889.34   
135847                                   Special Nurse   76305.74   
135853                                   Special Nurse   71178.15   
136063                                   Special Nurse   61276.59   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
135701         0.00    6550.41    771.88   77186.02          77957.90  2014   
135778      6815.67    9041.21    767.47   76746.22          77513.69  2014   
135847         0.00       0.00    763.08   76305.74          77068.82  2014   
135853      2748.15    2354.40    762.81   76280.70          77043.51  2014   
136063      8538.44    5078.67    748.95   74893.70          75642.65  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
135701    NaN  San Francisco     NaN  
135778    NaN  San Francisco     NaN  
135847    NaN  San Francisco     NaN  
135853    NaN  San Francisco     NaN  
136063    NaN  San Francisco     NaN  

[69489 rows x 13 columns]

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [ ]:
# YOUR CODE IS HERE


tot = df["TotalPay"].mean()



upp = (df['TotalPay'] > tot).sum()

upp

### How much does ALBERT PARDINI make money (including benefits)?

In [487]:
# YOUR CODE IS HERE

aaa =  df[df['EmployeeName'] == "ALBERT PARDINI"]
aaa

columns_to_sum = ['BasePay', 'OvertimePay', 'OtherPay' , "Benefits"] 

# Sadece seçili sütunların toplamını al
total_sum = aaa[columns_to_sum].sum(axis=1).values[0]
total_sum


np.float64(335279.91)

### Who is the lowest paid person?

In [501]:
# YOUR CODE IS HERE

vv = df[df['TotalPay'] == df['TotalPay'].min()][["EmployeeName", "TotalPay"]]
vv

EmployeeName  TotalPay
148653    Joe Lopez   -618.13

### What are the unique Jobs in dataset?

In [505]:
# YOUR CODE IS HERE

pd.unique(df["JobTitle"])

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], shape=(2159,), dtype=object)

### List the top 3 least common Jobs in the dataset.

In [509]:
# YOUR CODE IS HERE

sayi = df["JobTitle"].value_counts()

enaz = sayi.nsmallest(3)
enaz

JobTitle
DEPUTY DIRECTOR OF INVESTMENTS    1
Chief Forensic Toxicologist       1
Lieutenant (Police Department)    1
Name: count, dtype: int64

### How many people earned more than avg in 2012?

In [517]:
# YOUR CODE IS HERE

yil = df[df["Year"] == 2012]

ort = yil["TotalPay"].mean()

ust = (yil["TotalPay"] > ort).sum()
ust


np.int64(16944)

### How many people have a title of Manager in their jobs?

In [527]:
# USE APPLY FUNCTION

# YOUR CODE IS HERE
managers = df["JobTitle"].apply(lambda x: "Manager" in x).sum()
managers



np.int64(3080)

### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [537]:
# YOUR CODE IS HERE


sal_new = df.iloc[:, [0, 1, 2, 7, 8]]
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [541]:
# YOUR CODE IS HERE

sal_new = df.loc[:, ["EmployeeName", "TotalPayBenefits"]]
sal_new


EmployeeName  TotalPayBenefits
0          NATHANIEL FORD         567595.43
1            GARY JIMENEZ         538909.28
2          ALBERT PARDINI         335279.91
3       CHRISTOPHER CHONG         332343.61
4         PATRICK GARDNER         326373.19
...                   ...               ...
148649      Roy I Tillery              0.00
148650       Not provided              0.00
148651       Not provided              0.00
148652       Not provided              0.00
148653          Joe Lopez           -618.13

[148654 rows x 2 columns]

Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [ ]:
# YOUR CODE IS HERE
a=df["TotalPay"].min()
b=df["TotalPay"].mean()


c= df[(df["TotalPay"] > a) & (df["TotalPay"] < b)]


employee_names = c[["EmployeeName"]]

employee_names

EmployeeName
15847   TATYANA ROTENBERG
15848         WINSTON HOM
15849        CRAIG RIGLER
15850           WENDY TAN
15851      KENNETH BREWER
...                   ...
148648        Leon Walker
148649      Roy I Tillery
148650       Not provided
148651       Not provided
148652       Not provided

[79164 rows x 1 columns]

Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<hr>

<p style="background-color:#FDFEFE; font-family:newtimeroman; color:#635EA7; font-size:350%; text-align:center; border-radius:10px 10px;">End of The Assignment - 1</p>

# <span style="color:#DA55E5">**Now. it's time to relax!**<span>
    
![Image_Assignment](https://i.ibb.co/jZD3Mqb/relaxing.jpg)
   

<a href="https://ondiande.com/contact/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="ONDIA Contact" width="110" height="200" title="This notebook is licensed by ONDIA. Please contact the authorized persons about the conditions under which you can use or share."></a>